---
- name: Install Common Packages
  apt:
    pkg:
      - vim
      - git
      - curl
    state: present

- name: Install python3 
  apt:
    name: python3-apt
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install Nginx
  apt: 
    name:  nginx 
    update_cache: yes
    state: present