---
- hosts: all
  tasks:
  - name: Install pip
    apt: name=python3-pip state=present
    become: yes    
  
  - name: Install Flask
    command: pip3 install -U Flask
    become: yes 
  
  - name: Install requests
    apt: name=python3-requests state=present
    become: yes    
  
  - name: Ansible create app
    become: yes
    copy:
      dest: "/home/vagrant/main.py"
      content: |

        from flask import Flask
        import requests

        app = Flask(__name__)


        @app.route('/', methods=['GET'])
        def index():
            req = requests.get('https://animechan.vercel.app/api/random')
            
            return "Hello from IP" 

        if __name__ == '__main__':
                    app.run(debug = True, host='0.0.0.0', port='5000')
            
            
  - name: Insert IP
    shell: sed -i "s/IP/$(hostname)/g" /home/vagrant/main.py
    become: yes
  
  - name: Ansible create service for app
    become: yes
    copy:
      dest: "/etc/systemd/system/app.service"
      mode: 0664 
      owner: vagrant 
      content: | 
        [Unit]
        Description=my Flask app

        [Service]
        ExecStart=/usr/bin/python3 /home/vagrant/main.py

        [Install]
        WantedBy=multi-user.target
    
  - name: Start app
    become: yes
    systemd:   
      state: started 
      daemon_reload: yes 
      name: app.service
      enabled: yes 

